import type { Trip } from '../models/Trip';

export const SAMPLE_TRIPS: Trip[] = [
  {
    id: 't1',
    naziv: 'Japan: Tokyo, Kyoto i Osaka',
    opis: 'Dvonedeljno putovanje kroz tri grada — od neonskog Tokija do hramova Kjota i kuhinje Osake.',
    pocetak: '2026-04-08',
    kraj: '2026-04-21',
    budzet: 4800,
    valuta: 'EUR',
    kover: 'https://images.unsplash.com/photo-1492571350019-22de08371fd3?w=1200&q=80',
    boja: 'terra',
    napomene: 'Rezervisati JR Pass pre polaska. Proveriti vize.',
    destinacije: [
      {
        id: 'd1',
        naziv: 'Tokio',
        lokacija: 'Tokyo, Japan',
        dolazak: '2026-04-08',
        odlazak: '2026-04-13',
        opis: 'Shibuya, Shinjuku, Asakusa, Akihabara. Smeštaj u Shinjuku.',
        foto: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
      },
      {
        id: 'd2',
        naziv: 'Kjoto',
        lokacija: 'Kyoto, Japan',
        dolazak: '2026-04-13',
        odlazak: '2026-04-17',
        opis: 'Fushimi Inari, Arashiyama bambusova šuma, Kinkaku-ji.',
        foto: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80',
      },
      {
        id: 'd3',
        naziv: 'Osaka',
        lokacija: 'Osaka, Japan',
        dolazak: '2026-04-17',
        odlazak: '2026-04-21',
        opis: 'Dotonbori, Osaka Castle, dnevni izlet u Naru.',
        foto: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&q=80',
      },
    ],
    aktivnosti: [
      { id: 'a1', destId: 'd1', naziv: 'Sletanje na Narita aerodrom', datum: '2026-04-08', vreme: '14:30', lokacija: 'NRT Terminal 1', opis: 'Narita Express do hotela.', trosak: 30, status: 'rezervisano' },
      { id: 'a2', destId: 'd1', naziv: 'Šetnja kroz Shibuya Crossing', datum: '2026-04-09', vreme: '10:00', lokacija: 'Shibuya', opis: 'Hachiko spomenik, Shibuya Sky.', trosak: 25, status: 'planirano' },
      { id: 'a3', destId: 'd1', naziv: 'Sushi u Tsukiji marketu', datum: '2026-04-09', vreme: '13:00', lokacija: 'Tsukiji Outer Market', opis: 'Doručak / rana večera.', trosak: 45, status: 'planirano' },
      { id: 'a4', destId: 'd1', naziv: 'Robot show u Shinjuku', datum: '2026-04-09', vreme: '20:00', lokacija: 'Kabukicho', opis: '', trosak: 60, status: 'rezervisano' },
      { id: 'a5', destId: 'd1', naziv: 'TeamLab Planets', datum: '2026-04-10', vreme: '11:00', lokacija: 'Toyosu', opis: 'Imerzivna umetnička instalacija.', trosak: 35, status: 'rezervisano' },
      { id: 'a6', destId: 'd1', naziv: 'Asakusa & Senso-ji hram', datum: '2026-04-11', vreme: '09:00', lokacija: 'Asakusa', opis: '', trosak: 0, status: 'planirano' },
      { id: 'a7', destId: 'd1', naziv: 'Akihabara — elektronika', datum: '2026-04-12', vreme: '15:00', lokacija: 'Akihabara', opis: '', trosak: 80, status: 'planirano' },
      { id: 'a8', destId: 'd2', naziv: 'Shinkansen Tokio → Kjoto', datum: '2026-04-13', vreme: '08:30', lokacija: 'Tokyo Station', opis: 'Pokriveno JR Passom.', trosak: 0, status: 'rezervisano' },
      { id: 'a9', destId: 'd2', naziv: 'Fushimi Inari Taisha', datum: '2026-04-14', vreme: '07:00', lokacija: 'Fushimi', opis: 'Rano radi izbegavanja gužve.', trosak: 0, status: 'planirano' },
      { id: 'a10', destId: 'd2', naziv: 'Arashiyama bambusova šuma', datum: '2026-04-15', vreme: '09:00', lokacija: 'Arashiyama', opis: 'I Tenryu-ji hram.', trosak: 8, status: 'planirano' },
      { id: 'a11', destId: 'd2', naziv: 'Tea ceremonija u Gionu', datum: '2026-04-16', vreme: '15:00', lokacija: 'Gion', opis: '', trosak: 55, status: 'rezervisano' },
      { id: 'a12', destId: 'd3', naziv: 'Voz Kjoto → Osaka', datum: '2026-04-17', vreme: '10:00', lokacija: 'Kyoto Station', opis: '', trosak: 0, status: 'rezervisano' },
      { id: 'a13', destId: 'd3', naziv: 'Dotonbori — street food', datum: '2026-04-17', vreme: '19:00', lokacija: 'Dotonbori', opis: 'Takoyaki, okonomiyaki.', trosak: 40, status: 'planirano' },
      { id: 'a14', destId: 'd3', naziv: 'Osaka Castle', datum: '2026-04-18', vreme: '10:00', lokacija: 'Osaka-jo', opis: '', trosak: 6, status: 'planirano' },
      { id: 'a15', destId: 'd3', naziv: 'Dnevni izlet u Naru', datum: '2026-04-19', vreme: '08:00', lokacija: 'Nara Park', opis: 'Hraniti jelene.', trosak: 25, status: 'planirano' },
      { id: 'a16', destId: 'd3', naziv: 'Universal Studios Japan', datum: '2026-04-20', vreme: '09:00', lokacija: 'USJ', opis: '', trosak: 95, status: 'planirano' },
      { id: 'a17', destId: 'd3', naziv: 'Povratak — Kansai aerodrom', datum: '2026-04-21', vreme: '12:00', lokacija: 'KIX', opis: '', trosak: 35, status: 'rezervisano' },
    ],
    troskovi: [
      { id: 'e1', naziv: 'Avionske karte (povratne)', kategorija: 'prevoz', iznos: 1240, datum: '2026-02-01', opis: 'Lufthansa preko Frankfurta' },
      { id: 'e2', naziv: 'JR Pass 14 dana', kategorija: 'prevoz', iznos: 460, datum: '2026-03-15', opis: '' },
      { id: 'e3', naziv: 'Hotel Shinjuku (5 noći)', kategorija: 'smestaj', iznos: 680, datum: '2026-03-20', opis: 'Booking.com' },
      { id: 'e4', naziv: 'Ryokan Kjoto (4 noći)', kategorija: 'smestaj', iznos: 520, datum: '2026-03-20', opis: '' },
      { id: 'e5', naziv: 'Apartman Osaka (4 noći)', kategorija: 'smestaj', iznos: 380, datum: '2026-03-22', opis: 'Airbnb' },
      { id: 'e6', naziv: 'TeamLab Planets ulaznice', kategorija: 'ulaznice', iznos: 35, datum: '2026-03-25', opis: '' },
      { id: 'e7', naziv: 'Universal Studios Japan', kategorija: 'ulaznice', iznos: 95, datum: '2026-03-28', opis: '' },
      { id: 'e8', naziv: 'Putno osiguranje', kategorija: 'ostalo', iznos: 85, datum: '2026-03-10', opis: '' },
      { id: 'e9', naziv: 'eSIM 14 dana', kategorija: 'ostalo', iznos: 28, datum: '2026-04-01', opis: '' },
    ],
    checklist: [
      { id: 'c1', naziv: 'Pasoš (proveriti rok)', kategorija: 'dokumenti', zavrseno: true },
      { id: 'c2', naziv: 'Avionska karta — printati', kategorija: 'dokumenti', zavrseno: true },
      { id: 'c3', naziv: 'Putno osiguranje', kategorija: 'dokumenti', zavrseno: true },
      { id: 'c4', naziv: 'JR Pass voucher', kategorija: 'dokumenti', zavrseno: false },
      { id: 'c5', naziv: 'Univerzalni adapter (tip A)', kategorija: 'tehnika', zavrseno: true },
      { id: 'c6', naziv: 'Powerbank', kategorija: 'tehnika', zavrseno: false },
      { id: 'c7', naziv: 'Kamera + dodatne baterije', kategorija: 'tehnika', zavrseno: false },
      { id: 'c8', naziv: 'Udobne patike za hodanje', kategorija: 'garderoba', zavrseno: true },
      { id: 'c9', naziv: 'Lagana jakna (april = ~15°C)', kategorija: 'garderoba', zavrseno: false },
      { id: 'c10', naziv: 'Kišobran', kategorija: 'garderoba', zavrseno: false },
      { id: 'c11', naziv: 'Lijekovi i prva pomoć', kategorija: 'higijena', zavrseno: false },
      { id: 'c12', naziv: 'Kontaktna sočiva + naočale', kategorija: 'higijena', zavrseno: true },
    ],
  },
  {
    id: 't2',
    naziv: 'Vikend u Pragu',
    opis: 'Brz vikend izlet — Stari grad, Karlov most, lokalna piva.',
    pocetak: '2026-05-22',
    kraj: '2026-05-25',
    budzet: 650,
    valuta: 'EUR',
    kover: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&q=80',
    boja: 'forest',
    napomene: '',
    destinacije: [
      {
        id: 'd4',
        naziv: 'Prag',
        lokacija: 'Prague, Czech Republic',
        dolazak: '2026-05-22',
        odlazak: '2026-05-25',
        opis: '',
      },
    ],
    aktivnosti: [],
    troskovi: [
      { id: 'e10', naziv: 'Avionske karte', kategorija: 'prevoz', iznos: 180, datum: '2026-04-10', opis: '' },
      { id: 'e11', naziv: 'Hotel (3 noći)', kategorija: 'smestaj', iznos: 240, datum: '2026-04-12', opis: '' },
    ],
    checklist: [],
  },
  {
    id: 't3',
    naziv: 'Lisabon ljeto 2026',
    opis: 'U planu — još istražujemo destinaciju.',
    pocetak: '2026-07-15',
    kraj: '2026-07-22',
    budzet: 1400,
    valuta: 'EUR',
    kover: 'https://images.unsplash.com/photo-1588535401305-da8d2db14e69?w=1200&q=80',
    boja: 'gold',
    napomene: '',
    destinacije: [],
    aktivnosti: [],
    troskovi: [],
    checklist: [],
  },
];
